/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export { }
declare global {

    const computed: typeof import("vue")["computed"];
    const readonly: typeof import("vue")["readonly"];
    const ref: typeof import("vue")["ref"];


}

