// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/area_fence_info.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Mapservice.AreaInfo {
  /// <summary>
  /// 地图服务提供，以供中台调用
  /// </summary>
  public static partial class AreaFenceInfo
  {
    static readonly string __ServiceName = "mapservice.area_info.AreaFenceInfo";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Mapservice.AreaInfo.CheckPointInAreaReq> __Marshaller_mapservice_area_info_CheckPointInAreaReq = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Mapservice.AreaInfo.CheckPointInAreaReq.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Mapservice.AreaInfo.CheckPointInAreaResp> __Marshaller_mapservice_area_info_CheckPointInAreaResp = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Mapservice.AreaInfo.CheckPointInAreaResp.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Mapservice.AreaInfo.GetAreaBoundaryPointsReq> __Marshaller_mapservice_area_info_GetAreaBoundaryPointsReq = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Mapservice.AreaInfo.GetAreaBoundaryPointsReq.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Mapservice.AreaInfo.GetAreaBoundaryPointsResp> __Marshaller_mapservice_area_info_GetAreaBoundaryPointsResp = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Mapservice.AreaInfo.GetAreaBoundaryPointsResp.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Mapservice.AreaInfo.CheckPointInAreaReq, global::Mapservice.AreaInfo.CheckPointInAreaResp> __Method_CheckPointInArea = new grpc::Method<global::Mapservice.AreaInfo.CheckPointInAreaReq, global::Mapservice.AreaInfo.CheckPointInAreaResp>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CheckPointInArea",
        __Marshaller_mapservice_area_info_CheckPointInAreaReq,
        __Marshaller_mapservice_area_info_CheckPointInAreaResp);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Mapservice.AreaInfo.GetAreaBoundaryPointsReq, global::Mapservice.AreaInfo.GetAreaBoundaryPointsResp> __Method_GetAreaBoundaryPoints = new grpc::Method<global::Mapservice.AreaInfo.GetAreaBoundaryPointsReq, global::Mapservice.AreaInfo.GetAreaBoundaryPointsResp>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetAreaBoundaryPoints",
        __Marshaller_mapservice_area_info_GetAreaBoundaryPointsReq,
        __Marshaller_mapservice_area_info_GetAreaBoundaryPointsResp);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Mapservice.AreaInfo.AreaFenceInfoReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of AreaFenceInfo</summary>
    [grpc::BindServiceMethod(typeof(AreaFenceInfo), "BindService")]
    public abstract partial class AreaFenceInfoBase
    {
      /// <summary>
      /// 检查坐标是否在区域内
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Mapservice.AreaInfo.CheckPointInAreaResp> CheckPointInArea(global::Mapservice.AreaInfo.CheckPointInAreaReq request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// 通过area_ids获取一系列区域边界点集
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Mapservice.AreaInfo.GetAreaBoundaryPointsResp> GetAreaBoundaryPoints(global::Mapservice.AreaInfo.GetAreaBoundaryPointsReq request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for AreaFenceInfo</summary>
    public partial class AreaFenceInfoClient : grpc::ClientBase<AreaFenceInfoClient>
    {
      /// <summary>Creates a new client for AreaFenceInfo</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public AreaFenceInfoClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for AreaFenceInfo that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public AreaFenceInfoClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected AreaFenceInfoClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected AreaFenceInfoClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// 检查坐标是否在区域内
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Mapservice.AreaInfo.CheckPointInAreaResp CheckPointInArea(global::Mapservice.AreaInfo.CheckPointInAreaReq request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CheckPointInArea(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// 检查坐标是否在区域内
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Mapservice.AreaInfo.CheckPointInAreaResp CheckPointInArea(global::Mapservice.AreaInfo.CheckPointInAreaReq request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CheckPointInArea, null, options, request);
      }
      /// <summary>
      /// 检查坐标是否在区域内
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Mapservice.AreaInfo.CheckPointInAreaResp> CheckPointInAreaAsync(global::Mapservice.AreaInfo.CheckPointInAreaReq request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CheckPointInAreaAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// 检查坐标是否在区域内
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Mapservice.AreaInfo.CheckPointInAreaResp> CheckPointInAreaAsync(global::Mapservice.AreaInfo.CheckPointInAreaReq request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CheckPointInArea, null, options, request);
      }
      /// <summary>
      /// 通过area_ids获取一系列区域边界点集
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Mapservice.AreaInfo.GetAreaBoundaryPointsResp GetAreaBoundaryPoints(global::Mapservice.AreaInfo.GetAreaBoundaryPointsReq request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAreaBoundaryPoints(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// 通过area_ids获取一系列区域边界点集
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Mapservice.AreaInfo.GetAreaBoundaryPointsResp GetAreaBoundaryPoints(global::Mapservice.AreaInfo.GetAreaBoundaryPointsReq request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetAreaBoundaryPoints, null, options, request);
      }
      /// <summary>
      /// 通过area_ids获取一系列区域边界点集
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Mapservice.AreaInfo.GetAreaBoundaryPointsResp> GetAreaBoundaryPointsAsync(global::Mapservice.AreaInfo.GetAreaBoundaryPointsReq request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAreaBoundaryPointsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// 通过area_ids获取一系列区域边界点集
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Mapservice.AreaInfo.GetAreaBoundaryPointsResp> GetAreaBoundaryPointsAsync(global::Mapservice.AreaInfo.GetAreaBoundaryPointsReq request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetAreaBoundaryPoints, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override AreaFenceInfoClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new AreaFenceInfoClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(AreaFenceInfoBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_CheckPointInArea, serviceImpl.CheckPointInArea)
          .AddMethod(__Method_GetAreaBoundaryPoints, serviceImpl.GetAreaBoundaryPoints).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, AreaFenceInfoBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_CheckPointInArea, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Mapservice.AreaInfo.CheckPointInAreaReq, global::Mapservice.AreaInfo.CheckPointInAreaResp>(serviceImpl.CheckPointInArea));
      serviceBinder.AddMethod(__Method_GetAreaBoundaryPoints, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Mapservice.AreaInfo.GetAreaBoundaryPointsReq, global::Mapservice.AreaInfo.GetAreaBoundaryPointsResp>(serviceImpl.GetAreaBoundaryPoints));
    }

  }
}
#endregion
